# Generated by Django 3.1.2 on 2020-10-04 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestoday',
            old_name='oblast',
            new_name='population',
        ),
    ]
