# Generated by Django 3.1.2 on 2020-10-04 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20201004_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestoday',
            name='oblast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.population'),
        ),
    ]
