# Generated by Django 3.1.2 on 2020-10-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20201004_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestoday',
            name='indx',
            field=models.FloatField(null=True),
        ),
    ]
