# Generated by Django 3.1.2 on 2020-10-05 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20201005_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestoday',
            old_name='oblast',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='population',
            old_name='oblast',
            new_name='region',
        ),
    ]
