# Generated by Django 3.1.2 on 2020-10-05 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20201005_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.population'),
        ),
    ]
