# Generated by Django 3.1.2 on 2020-10-05 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_map_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestoday',
            name='map',
        ),
        migrations.AddField(
            model_name='map',
            name='cases',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.casestoday'),
        ),
    ]
