# Generated by Django 3.1.2 on 2020-10-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20201005_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestoday',
            name='color',
            field=models.FloatField(null=True),
        ),
    ]
