# Generated by Django 3.1.2 on 2020-10-06 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_mapcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapcomment',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(3, "Hey! Don't be so shy")]),
        ),
    ]
