# Generated by Django 3.1.2 on 2020-10-06 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_auto_20201006_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapcomment',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(3, 'Comment must be greater than 3 characters')]),
        ),
    ]
