# Generated by Django 3.2.15 on 2022-10-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20221008_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='featured',
            new_name='posted',
        ),
    ]
